### ISSUE TITLE
extract_topo_param() from Topoclass fails, when running with the version in current main branch.

### ISSUE THREAD

**Issue by paswyss** [ArcticSnow/TopoPyScale#51]
execution:
mp = tc.Topoclass(config_file)
mp.compute_dem_param()
mp.extract_topo_param()

-> Same would work correctly with environment with release version of topopyscale in it.

**Terminal output**
Traceback (most recent call last):
  File "pipeline.py", line 9, in <module>
    mp.extract_topo_param()
  File ".../TopoPyScale/TopoPyScale/topoclass.py", line 308, in extract_topo_param
    self.extract_topo_cluster_param()
  File ".../TopoPyScale/TopoPyScale/topoclass.py", line 261, in extract_topo_cluster_param
    df_scaled, self.toposub.scaler = ts.scale_df(df_param, features=self.config.sampling.toposub.clustering_features)
  File ".../TopoPyScale/TopoPyScale/topo_sub.py", line 56, in scale_df
    df_scaled = pd.DataFrame(scaler.fit_transform(df_param[feature_list].values),
  File "...miniconda3/envs/TopoPyScaleClone/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 142, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "...miniconda3/envs/TopoPyScaleClone/lib/python3.8/site-packages/sklearn/base.py", line 859, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "...miniconda3/envs/TopoPyScaleClone/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 824, in fit
    return self.partial_fit(X, y, sample_weight)
  File "...miniconda3/envs/TopoPyScaleClone/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 861, in partial_fit
    X = self._validate_data(
  File "...miniconda3/envs/TopoPyScaleClone/lib/python3.8/site-packages/sklearn/base.py", line 546, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "...miniconda3/envs/TopoPyScaleClone/lib/python3.8/site-packages/sklearn/utils/validation.py", line 940, in check_array
    raise ValueError(

**Comment by ArcticSnow** [comment]
Hi @paswyss ,
I have not encountered this prb with the current commit in the `main` branch. how is your config file? I introduced a new config parameter : 
```
clustering_features: {'x':1, 'y':1, 'elevation':4, 'slope':1, 'aspect_cos':1, 'aspect_sin':1, 'svf':1}
```
https://topopyscale.readthedocs.io/en/latest/3_configurationFile/

Could that be the error?

**Comment by paswyss** [comment]
This was indeed the error, now it works fine, thanks :)
When does the example repository (https://github.com/ArcticSnow/TopoPyScale_examples) get updated? After each new release?
