### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'lat'

### ISSUE THREAD

**Issue by NILICK** [ArcticSnow/TopoPyScale#96]
It seems that there is a mistake in lines (141-142) of `topo_scale.py` file:

        ind_lat = np.abs(ds_.latitude - row.lat).argmin()
        ind_lon = np.abs(ds_.longitude - row.lon).argmin()

With the current code, I got the below error:

```
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/IPython/core/magics/execution.py", line 1317, in time
    out = eval(code, glob, local_ns)
  File "<timed eval>", line 3, in <module>
  File .../topopyscale/lib/python3.9/site-packages/TopoPyScale/topoclass.py", line 496, in downscale_climate
    ta.downscale_climate(self.config.project.directory,
  File ".../topopyscale/lib/python3.9/site-packages/TopoPyScale/topo_scale.py", line 209, in downscale_climate
    multithread_pooling(_subset_climate_dataset, fun_param, n_threads=n_core)
  File ".../topopyscale/lib/python3.9/site-packages/TopoPyScale/topo_scale.py", line 89, in multithread_pooling
    tpool.starmap(fun, fun_param)
  File ".../topopyscale/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File ".../topopyscale/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File ".../topopyscale/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File ".../topopyscale/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File ".../topopyscale/lib/python3.9/site-packages/TopoPyScale/topo_scale.py", line 177, in _subset_climate_dataset
    ind_lat = np.abs(ds_.latitude - row.lat).argmin()
  File ".../topopyscale/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'lat'
```

But when I changed lines (141-142) of `topo_scale.py` file to:

        ind_lat = np.abs(ds_.latitude - row.latitude).argmin()
        ind_lon = np.abs(ds_.longitude - row.longitude).argmin()

then It runs without error.
Do these lines need to improve as above?

**Comment by ArcticSnow** [comment]
hello @NILICK , I am surprise by the bug you encountered as this has ran smoothly until in this configuration. 

`row` iterates over the row of `df_centroids` which is defined here: https://github.com/ArcticSnow/TopoPyScale/blob/4d1d3b772850ea8af86ed80c138f16d479200b58/TopoPyScale/topoclass.py#L358

Did you modify the name of the columns of `df_centroids` somewhere in your code?

**Comment by ArcticSnow** [comment]
What is `mp.topotsub.df_centroids.columns` showing in your project?
